// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZQGx0t6NbpSoTnQ9aIOGJM3x8IYMRRvY',
    appId: '1:501410510498:web:8b4576c65ad522102bc9fb',
    messagingSenderId: '501410510498',
    projectId: 'gamescollections-e9a7c',
    authDomain: 'gamescollections-e9a7c.firebaseapp.com',
    databaseURL: 'https://gamescollections-e9a7c-default-rtdb.firebaseio.com',
    storageBucket: 'gamescollections-e9a7c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9FDzp5N78Wke4HskK1vWR44LdtMe_yX0',
    appId: '1:501410510498:ios:c17fe55bd17f3cbd2bc9fb',
    messagingSenderId: '501410510498',
    projectId: 'gamescollections-e9a7c',
    databaseURL: 'https://gamescollections-e9a7c-default-rtdb.firebaseio.com',
    storageBucket: 'gamescollections-e9a7c.appspot.com',
    iosBundleId: 'com.example.gamesColletions',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9FDzp5N78Wke4HskK1vWR44LdtMe_yX0',
    appId: '1:501410510498:ios:c17fe55bd17f3cbd2bc9fb',
    messagingSenderId: '501410510498',
    projectId: 'gamescollections-e9a7c',
    databaseURL: 'https://gamescollections-e9a7c-default-rtdb.firebaseio.com',
    storageBucket: 'gamescollections-e9a7c.appspot.com',
    iosBundleId: 'com.example.gamesColletions',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk7bLMmoK3_zy-14ELuGvbZjQGOHEmMxY',
    appId: '1:501410510498:android:bc5a22eaf39f5df82bc9fb',
    messagingSenderId: '501410510498',
    projectId: 'gamescollections-e9a7c',
    databaseURL: 'https://gamescollections-e9a7c-default-rtdb.firebaseio.com',
    storageBucket: 'gamescollections-e9a7c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZQGx0t6NbpSoTnQ9aIOGJM3x8IYMRRvY',
    appId: '1:501410510498:web:fe84a8c74ae772462bc9fb',
    messagingSenderId: '501410510498',
    projectId: 'gamescollections-e9a7c',
    authDomain: 'gamescollections-e9a7c.firebaseapp.com',
    databaseURL: 'https://gamescollections-e9a7c-default-rtdb.firebaseio.com',
    storageBucket: 'gamescollections-e9a7c.appspot.com',
  );

}