// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArJuxR0oBgRZYF_92wZ4mIRyvL586qpxY',
    appId: '1:592485418564:web:daf66c252369e6ae805e11',
    messagingSenderId: '592485418564',
    projectId: 'gamescollections-a1b1a',
    authDomain: 'gamescollections-a1b1a.firebaseapp.com',
    storageBucket: 'gamescollections-a1b1a.appspot.com',
    measurementId: 'G-DGSZZD12L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARXTW2-Elq19hfDZap5_W3u3EAoWbGTkw',
    appId: '1:592485418564:android:17d1deac6c046357805e11',
    messagingSenderId: '592485418564',
    projectId: 'gamescollections-a1b1a',
    storageBucket: 'gamescollections-a1b1a.appspot.com',
  );

}